package shootingstar.var.enums.type;

public enum PointOriginType {
    AUCTION_REGISTRATION_DEPOSIT, BID, VIP_AUCTION_CANCEL, ADMIN_AUCTION_CANCEL, WINNER_TICKET_CANCEL, ORGANIZER_TICKET_CANCEL, TICKET_COMPLETE, CHARGE, EXCHANGE
}
